const fs=require('fs');
const path=require('path');
const vm=require('vm');
const ROOT=__dirname;
const context={window:{}};vm.createContext(context);
for(const file of ['i18n-en-us-phrases-1.js','i18n-en-us-phrases-2.js','i18n-en-us-phrases-3.js','i18n-en-us-words.js','i18n-en-us-words-extra-1.js','i18n-en-us-words-extra-2.js','i18n-en-us-words-extra-3.js','i18n-en-us-words-extra-4.js'])vm.runInContext(fs.readFileSync(path.join(ROOT,file),'utf8'),context,{filename:file});

const runtimePhrases=[
 ['MÃO VIVA','LIVE HAND'],['MÃOS VIVAS','LIVE HANDS'],['QUEM AGE PRIMEIRO','WHO ACTS FIRST'],['QUEM AGE POR ÚLTIMO','WHO ACTS LAST'],['AGE PRIMEIRO','ACTS FIRST'],['AGE POR ÚLTIMO','ACTS LAST'],['AGE ANTES','ACTS BEFORE'],['AGE DEPOIS','ACTS AFTER'],['DEALER CONFERE','DEALER CHECKS'],['O DEALER CONFERE','THE DEALER CHECKS'],['BLINDS/ANTES','BLINDS/ANTES'],['BLINDS / ANTES','BLINDS / ANTES'],['BLINDS E ANTES','BLINDS AND ANTES'],['BLINDS E, QUANDO APLICÁVEL, ANTES','BLINDS AND, WHEN APPLICABLE, ANTES'],['OS NÍVEIS ELEVAM BLINDS/ANTES AO LONGO DO EVENTO.','THE LEVELS INCREASE BLINDS/ANTES THROUGHOUT THE EVENT.'],['ANTES JÁ FORMAM O POTE','ANTES ALREADY FORM THE POT'],['ANTES SÃO DEVOLVIDOS','ANTES ARE RETURNED']
];
const runtimeWords={protege:'protects',protegem:'protect',cassino:'casino',cassinos:'casinos',dupla:'pair',duplas:'pairs',ajustar:'adjust',ajusta:'adjusts',ajuste:'adjustment',decisao:'decision','decisão':'decision',decisoes:'decisions','decisões':'decisions',resultado:'result',resultados:'results',confere:'checks',conferem:'check',viva:'live',vivas:'live',vivo:'live',vivos:'live',contra:'against','compara-se':'compare','comparam-se':'compare','divide-se':'is split','aproxima-se':'is closer','refere-se':'refers','soma-se':'add','aplica-se':'applies','trata-se':'this is','torna-se':'becomes','mantém-se':'remains','encontra-se':'is',conectividade:'connectivity',movimentando:'moving',aplicam:'apply'};
const phrasePairs=runtimePhrases.concat(context.window.StackupI18nPhrases||[]).slice().sort((a,b)=>b[0].length-a[0].length);
const words=Object.assign({},context.window.StackupI18nWords||{},runtimeWords);
const failures=[];let checks=0;const check=(name,ok,detail='')=>{checks++;if(!ok)failures.push(`${name}${detail?`: ${detail}`:''}`);};
function escapeRegExp(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function matchCase(source,target){if(source===source.toUpperCase())return target.toUpperCase();if(source===source.toLowerCase())return target.toLowerCase();if(source[0]&&source[0]===source[0].toUpperCase())return target.charAt(0).toUpperCase()+target.slice(1);return target;}
function phraseRegex(pt){const body=escapeRegExp(pt),sw=/^[\p{L}\p{M}\p{N}]/u.test(pt),ew=/[\p{L}\p{M}\p{N}]$/u.test(pt);return new RegExp(`${sw?'(?<![\\p{L}\\p{M}\\p{N}])':''}${body}${ew?'(?![\\p{L}\\p{M}\\p{N}])':''}`,'giu');}
function protectPokerNotation(input){const slots=[];const hold=v=>{const i=slots.push(v)-1;return `\uE100${i}\uE101`;};let out=String(input);out=out.replace(/(?:10|[2-9AKQJ])[♠♥♦♣]/g,hold).replace(/\b(?:10|[2-9AKQJ])(?:-(?:10|[2-9AKQJ])){1,8}\b/g,hold).replace(/\b(?:[AKQJT2-9]{2})(?:s|o)?\b/g,hold);return{out,restore:v=>v.replace(/\uE100(\d+)\uE101/g,(_,i)=>slots[Number(i)]||'')};}
function translate(input){if(!input||!/[A-Za-zÀ-ÿ]/.test(input))return input;if(/^(?:10|[2-9AKQJ])$/.test(String(input).trim()))return input;const p=protectPokerNotation(input);let out=p.out;const slots=[];for(const[pt,en]of phrasePairs)out=out.replace(phraseRegex(pt),m=>{const i=slots.push(matchCase(m,en))-1;return`\uE000${i}\uE001`;});out=out.replace(/[\p{L}\p{M}]+(?:[-’'][\p{L}\p{M}]+)*/gu,t=>{const tr=words[t.toLocaleLowerCase('pt-BR')];return tr?matchCase(t,tr):t;});out=out.replace(/\uE000(\d+)\uE001/g,(_,i)=>slots[Number(i)]||'');return p.restore(out);}

check('large phrase catalog',phrasePairs.length>=410,`found ${phrasePairs.length}`);check('large word catalog',Object.keys(words).length>=3010,`found ${Object.keys(words).length}`);
check('Ace notation preserved',translate('A♠ K♠ A-K-Q-J-10')==='A♠ K♠ A-K-Q-J-10',translate('A♠ K♠ A-K-Q-J-10'));check('standalone Ace preserved',translate('A')==='A',translate('A'));check('INFORMAÇÃO boundary',translate('INFORMAÇÃO')==='INFORMATION',translate('INFORMAÇÃO'));check('no informaction regression',!translate('INFORMAÇÃO').toLowerCase().includes('informaction'),translate('INFORMAÇÃO'));
for(const [pt,en] of Object.entries({protege:'protects',cassino:'casino',duplas:'pairs',ajustar:'adjust',decisao:'decision',resultado:'result',contra:'against',conectividade:'connectivity',movimentando:'moving',aplicam:'apply'}))check(`runtime word ${pt}`,translate(pt).toLowerCase()===en,translate(pt));
check('reflexive compara-se',!translate('compara-se').toLowerCase().includes('compara-se'),translate('compara-se'));check('reflexive divide-se',!translate('divide-se').toLowerCase().includes('divide-se'),translate('divide-se'));check('live hand phrase',translate('mão viva').toLowerCase()==='live hand',translate('mão viva'));check('acts first phrase',translate('quem age primeiro').toLowerCase()==='who acts first',translate('quem age primeiro'));check('poker antes protected',translate('blinds/antes').toLowerCase()==='blinds/antes',translate('blinds/antes'));

const sourceFiles=fs.readdirSync(ROOT).filter(f=>/\.(?:js|html)$/.test(f)&&!f.startsWith('i18n-en-us')&&!f.startsWith('test-')&&!f.startsWith('audit-'));
const unmappedAccented=new Map();for(const file of sourceFiles){const src=fs.readFileSync(path.join(ROOT,file),'utf8');for(const token of src.match(/[\p{L}\p{M}]+(?:[-’'][\p{L}\p{M}]+)*/gu)||[]){const k=token.toLocaleLowerCase('pt-BR');if(/[áàâãéêíóôõúç]/i.test(token)&&!Object.prototype.hasOwnProperty.call(words,k)&&k!=='aã'){if(!unmappedAccented.has(k))unmappedAccented.set(k,new Set());unmappedAccented.get(k).add(file);}}}
check('all accented Portuguese source words mapped',unmappedAccented.size===0,[...unmappedAccented].map(([w,f])=>`${w} (${[...f].join(',')})`).join('; '));

const ptWords=new Set(`para por sem depois como voce você voces vocês qual quais quem jogador jogadores mao mão maos mãos carta cartas pote ficha fichas aposta apostas apostar regra regras rodada rodadas posicao posição posicoes posições torneio torneios modalidade modalidades baralho distribuicao distribuição acao ação acoes ações deve devem pode podem precisa precisam cada todos todas nenhum nenhuma melhor melhores pior piores vence vencem perde perdem recebe recebem joga jogam jogar usar usa usam objetivo objetivos correto correta incorreto incorreta proximo próximo proximos próximos proxima próxima proximas próximas voltar etapa etapas fundamentos pratica prática matematica matemática pergunta perguntas resposta respostas explicacao explicação explicacoes explicações vencedor vencedores contra compara comparam divide aproxima refere soma confere conferem viva vivas protege protegem cassino cassinos dupla duplas ajustar ajusta ajuste decisao decisão decisoes decisões resultado resultados conectividade movimentando aplicam`.split(/\s+/).map(x=>x.toLocaleLowerCase('pt-BR')));
const portugueseSuffix=/(?:ções|ção|dades|dade|agens|agem|eiros|eiras|eiro|eira|ando|endo|indo|ariam|eriam|iriam|ávamos|íamos)$/iu;
const literal=/('(?:\\.|[^'\\])*'|"(?:\\.|[^"\\])*"|`(?:\\.|[^`\\])*`)/gs;const residue=[];
for(const file of sourceFiles){const src=fs.readFileSync(path.join(ROOT,file),'utf8');for(const m of src.matchAll(literal)){let raw=m[0].slice(1,-1);if(raw.length>5000)continue;if(raw.includes('{')&&raw.includes('}')&&/[:;]/.test(raw))continue;raw=raw.replace(/\\n|\\t/g,' ').replace(/\$\{[^}]*\}/g,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&(?:#\d+|\w+);/g,' ');if(!/[A-Za-zÀ-ÿ]/.test(raw))continue;const sourceTokens=raw.match(/[\p{L}\p{M}]+(?:-[\p{L}\p{M}]+)*/gu)||[];const looksPt=sourceTokens.some(t=>/[áàâãéêíóôõúç]/i.test(t)||ptWords.has(t.toLocaleLowerCase('pt-BR'))||/-se$/iu.test(t));if(!looksPt)continue;const out=translate(raw),tokens=out.match(/[\p{L}\p{M}]+(?:-[\p{L}\p{M}]+)*/gu)||[];const bad=tokens.filter(t=>{const k=t.toLocaleLowerCase('pt-BR');return /[áàâãéêíóôõúç]/i.test(t)||ptWords.has(k)||/-se$/iu.test(t)||portugueseSuffix.test(t);});if(bad.length)residue.push(`${file}: ${[...new Set(bad)].join(', ')} :: ${out.replace(/\s+/g,' ').slice(0,280)}`);}}
check('zero high-confidence Portuguese residue after EN-US translation',residue.length===0,residue.slice(0,100).join(' | '));

const index=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');check('logo preserved',index.includes('src="./header-logo-transparent.png?v=1"'));check('Love Ya Like A Sister preserved',index.includes("family=Love+Ya+Like+A+Sister")&&index.includes("font-family:'Love Ya Like A Sister',cursive"));const sw=fs.readFileSync(path.join(ROOT,'sw.js'),'utf8');check('service worker current',/stackup-academy-v6[89]/.test(sw)&&/SW_VERSION=6[89]/.test(sw));
if(failures.length){console.error(`i18n audit: ${checks-failures.length}/${checks} passed, ${failures.length} failed`);for(const f of failures)console.error(`FAIL: ${f}`);process.exit(1);}console.log(`i18n audit: ${checks}/${checks} passed`);console.log(`phrases: ${phrasePairs.length}; word mappings: ${Object.keys(words).length}; source files audited: ${sourceFiles.length}`);
